In [1]:
import numpy as np

In [4]:
# creatting the one d array
arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.shape)

[1 2 3 4]
(4,)


In [ ]:
arr2=np.array([1,2,3,4])
arr2.reshape(1,4) # 1 and 5 columns

(4,)


In [10]:
arr2=np.array([[1,2,3,4]])
print(arr2)


[[1 2 3 4]]


In [12]:
arr2=np.array([[1,2,3,4],[4,6,8,9]])
print(arr2)
print(arr2.shape)


[[1 2 3 4]
 [4 6 8 9]]
(2, 4)


In [ ]:
## creating the arraye by the help of the inbuilt function 
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1,10,2).reshape(1,5)

array([[1, 3, 5, 7, 9]])

In [25]:
# creating the ones array 
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# crating the dingonal value one by the help of the eye function 
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
# n8mpy vectorised array opertion
arr1=np.array([1,3,5,9,5,6])
arr2=np.array([3,5,9,5,6,5])
print('add the array elements',arr1+arr2)
print('add the array elements',arr1-arr2)
print('add the array elements',arr1*arr2)
print('add the array elements',arr1/arr2)



add the array elements [ 4  8 14 14 11 11]
add the array elements [-2 -2 -4  4 -1  1]
add the array elements [ 3 15 45 45 30 30]
add the array elements [0.33333333 0.6        0.55555556 1.8        0.83333333 1.2       ]


In [34]:
## Using the some Universal function 
arr1=np.array([2,3,4,5,6,7])
print(np.sqrt(arr1))
print(np.log(arr1))
print(np.sin(arr1))

[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]


In [35]:
## Indexing and the sciling used nto the numpy 
arr1=np.array([[1,2,3,4],[2,4,6,8],[1,3,5,7]])
print(arr1)

[[1 2 3 4]
 [2 4 6 8]
 [1 3 5 7]]


In [41]:
# print(arr1[row][colum])
print(arr1[0][3])

4


In [42]:
## Statistical concept Normalization
## the mean of the data is 0 and stv is 1 
data=np.array([1,2,3,4,5])
## calculating the mean of the data 
mean=np.mean(data)
# calculating the stanared daviation of the data
std_data=np.std(data)
## Normalization data 
normalized_data=(data-mean)/std_data
print('Normalization data',normalized_data)


Normalization data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
data=np.array([1,2,3,4,5])

mean=np.mean(data)
print('Mean',mean)
# calculating median 
median=np.median(data)
print('Median',median)
# calculating the mode
# print('Mode',np.mod(data))
#Calculating the variance and standerd Devince
print('Variance',np.var(data))
# calculating the standerd deviation 
print('Standersd Deviation',np.std(data))

Mean 3.0
Median 3.0
Variance 2.0
Standersd Deviation 1.4142135623730951
